import {
  Activity,
  AlertCircle,
  Archive,
  ArrowLeft,
  Banknote,
  Bell,
  Box,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Copy,
  CreditCard,
  Download,
  Droplet,
  EyeOff,
  File,
  Filter,
  Flame,
  Hammer,
  Heart,
  Home,
  ImageOff,
  Images,
  Key,
  Landmark,
  LayoutGrid,
  Link2,
  List,
  Loader2,
  Lock,
  LogOut,
  type LucideProps,
  Mail,
  MapPin,
  MapPinOff,
  Maximize2,
  MoreVertical,
  Move,
  Nfc,
  Paperclip,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  PieChart,
  Plus,
  Printer,
  QrCode,
  Receipt,
  RefreshCw,
  Repeat,
  RotateCcw,
  RotateCw,
  Router,
  ScanBarcode,
  ScanLine,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Tag,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  Users,
  Wallet,
  Wind,
  X,
  Zap,
} from "lucide-react";

// Single icon registry, per PRD §3: one rounded 24px line-icon family
// (lucide-react), used everywhere real iconography is needed instead of
// text glyphs.
const ICONS = {
  home: Home,
  box: Box,
  heart: Heart,
  settings: Settings,
  search: Search,
  camera: Camera,
  plus: Plus,
  close: X,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  arrowLeft: ArrowLeft,
  edit: Pencil,
  eyeOff: EyeOff,
  trash: Trash2,
  tag: Tag,
  user: User,
  users: Users,
  key: Key,
  qrCode: QrCode,
  archive: Archive,
  move: Move,
  panelLeftClose: PanelLeftClose,
  panelLeftOpen: PanelLeftOpen,
  needsReview: AlertCircle,
  check: Check,
  imageOff: ImageOff,
  gallery: Images,
  scan: ScanLine,
  scanBarcode: ScanBarcode,
  spinner: Loader2,
  moreVertical: MoreVertical,
  filter: Filter,
  upload: Upload,
  download: Download,
  logOut: LogOut,
  danger: ShieldAlert,
  restore: RotateCcw,
  rotate: RotateCw,
  ai: Sparkles,
  activity: Activity,
  copy: Copy,
  refresh: RefreshCw,
  attachment: Paperclip,
  file: File,
  bell: Bell,
  mail: Mail,
  pin: MapPin,
  printer: Printer,
  nfc: Nfc,
  smartphone: Smartphone,
  grid: LayoutGrid,
  list: List,
  mapPinOff: MapPinOff,
  maximize: Maximize2,
  link: Link2,
  shieldCheck: ShieldCheck,
  // Finance domain (docs/Personal Finance PRD.md §35 "Major components")
  wallet: Wallet,
  landmark: Landmark,
  creditCard: CreditCard,
  receipt: Receipt,
  trendingUp: TrendingUp,
  pieChart: PieChart,
  repeat: Repeat,
  lock: Lock,
  cash: Banknote,
  target: Target,
  trendingDown: TrendingDown,
  // Home Map (PRD §29) — one icon per pinned_locations category.
  droplet: Droplet,
  zap: Zap,
  flame: Flame,
  wind: Wind,
  router: Router,
  hammer: Hammer,
} as const;

export type IconName = keyof typeof ICONS;

export function Icon({ name, className, ...props }: { name: IconName } & LucideProps) {
  const Component = ICONS[name];
  return <Component className={className} strokeWidth={2} {...props} />;
}
