import {
  Activity,
  AlertCircle,
  Archive,
  ArrowLeft,
  Bell,
  Box,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  Copy,
  Download,
  File,
  Filter,
  Heart,
  Home,
  ImageOff,
  Images,
  Key,
  Loader2,
  LogOut,
  type LucideProps,
  MapPin,
  MoreVertical,
  Move,
  Paperclip,
  Pencil,
  Plus,
  Printer,
  QrCode,
  RefreshCw,
  RotateCcw,
  ScanLine,
  Search,
  Settings,
  ShieldAlert,
  Sparkles,
  Tag,
  Trash2,
  Upload,
  User,
  Users,
  X,
} from "lucide-react";

// Single icon registry, per PRD §3: one rounded 24px line-icon family
// (lucide-react), used everywhere real iconography is needed instead of
// text glyphs.
const ICONS = {
  home: Home,
  box: Box,
  heart: Heart,
  settings: Settings,
  search: Search,
  camera: Camera,
  plus: Plus,
  close: X,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  arrowLeft: ArrowLeft,
  edit: Pencil,
  trash: Trash2,
  tag: Tag,
  user: User,
  users: Users,
  key: Key,
  qrCode: QrCode,
  archive: Archive,
  move: Move,
  needsReview: AlertCircle,
  check: Check,
  imageOff: ImageOff,
  gallery: Images,
  scan: ScanLine,
  spinner: Loader2,
  moreVertical: MoreVertical,
  filter: Filter,
  upload: Upload,
  download: Download,
  logOut: LogOut,
  danger: ShieldAlert,
  restore: RotateCcw,
  ai: Sparkles,
  activity: Activity,
  copy: Copy,
  refresh: RefreshCw,
  attachment: Paperclip,
  file: File,
  bell: Bell,
  pin: MapPin,
  printer: Printer,
} as const;

export type IconName = keyof typeof ICONS;

export function Icon({ name, className, ...props }: { name: IconName } & LucideProps) {
  const Component = ICONS[name];
  return <Component className={className} strokeWidth={2} {...props} />;
}
